global:
  scrape_interval: 5s

  external_labels:
    monitor: 'monitoring'

scrape_configs:
  - job_name: 'fastapi-monitoring'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8000']