name: CI Python Application

on:
  push:
  pull_request:
    branches: 
      - main
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Build application
        run : echo "Build program"
    
  test-job:
    runs-on: ubuntu-latest
    
    needs: [build-job]
    
    steps:
      - name: This task run kind test 1
        run : echo "Run kind test 1"
      - name: This task run kind test 2
        run : echo "Run kind test 2"

    
  
      
